=begin
#Lob

#The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 

The version of the OpenAPI document: 1.3.0
Contact: lob-openapi@lob.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'date'
require 'time'

module OpenapiClient
  class CountryExtendedExpanded
    EMPTY = "".freeze
    AFGHANISTAN = "AFGHANISTAN".freeze
    ALBANIA = "ALBANIA".freeze
    ALGERIA = "ALGERIA".freeze
    AMERICAN_SAMOA = "AMERICAN SAMOA".freeze
    ANDORRA = "ANDORRA".freeze
    ANGOLA = "ANGOLA".freeze
    ANGUILLA = "ANGUILLA".freeze
    ANTARCTICA = "ANTARCTICA".freeze
    ANTIGUA_AND_BARBUDA = "ANTIGUA AND BARBUDA".freeze
    ARGENTINA = "ARGENTINA".freeze
    ARUBA = "ARUBA".freeze
    AUSTRALIA = "AUSTRALIA".freeze
    AUSTRIA = "AUSTRIA".freeze
    AZERBAIJAN = "AZERBAIJAN".freeze
    BAHRAIN = "BAHRAIN".freeze
    BANGLADESH = "BANGLADESH".freeze
    BARBADOS = "BARBADOS".freeze
    BELARUS = "BELARUS".freeze
    BELGIUM = "BELGIUM".freeze
    BELIZE = "BELIZE".freeze
    BENIN = "BENIN".freeze
    BERMUDA = "BERMUDA".freeze
    BHUTAN = "BHUTAN".freeze
    BOLIVIA__PLURINATIONAL_STATE_OF = "BOLIVIA (PLURINATIONAL STATE OF)".freeze
    BONAIRE_SAINT_EUSTATIUS_AND_SABA = "BONAIRE, SAINT EUSTATIUS AND SABA".freeze
    BOSNIA_AND_HERZEGOVINA = "BOSNIA AND HERZEGOVINA".freeze
    BOTSWANA = "BOTSWANA".freeze
    BRAZIL = "BRAZIL".freeze
    BRITISH_INDIAN_OCEAN_TERRITORY = "BRITISH INDIAN OCEAN TERRITORY".freeze
    BRITISH_VIRGIN_ISLANDS = "BRITISH VIRGIN ISLANDS".freeze
    BRUNEI_DARUSSALAM = "BRUNEI DARUSSALAM".freeze
    BULGARIA = "BULGARIA".freeze
    BURKINA_FASO = "BURKINA FASO".freeze
    BURUNDI = "BURUNDI".freeze
    CABO_VERDE = "CABO VERDE".freeze
    CAMBODIA = "CAMBODIA".freeze
    CAMEROON = "CAMEROON".freeze
    CANADA = "CANADA".freeze
    CAYMAN_ISLANDS = "CAYMAN ISLANDS".freeze
    CENTRAL_AFRICAN_REPUBLIC = "CENTRAL AFRICAN REPUBLIC".freeze
    CHAD = "CHAD".freeze
    CHILE = "CHILE".freeze
    CHINA = "CHINA".freeze
    COLOMBIA = "COLOMBIA".freeze
    COMOROS = "COMOROS".freeze
    CONGO = "CONGO".freeze
    CONGO_DEMOCRATIC_REPUBLIC_OF_THE = "CONGO, DEMOCRATIC REPUBLIC OF THE".freeze
    COOK_ISLANDS = "COOK ISLANDS".freeze
    COSTA_RICA = "COSTA RICA".freeze
    CTE_DIVOIRE = "CÔTE D`IVOIRE".freeze
    CROATIA = "CROATIA".freeze
    CUBA = "CUBA".freeze
    CURAAO = "CURAÇAO".freeze
    CYPRUS = "CYPRUS".freeze
    CZECH_REPUBLIC = "CZECH REPUBLIC".freeze
    DENMARK = "DENMARK".freeze
    DJIBOUTI = "DJIBOUTI".freeze
    DOMINICA = "DOMINICA".freeze
    DOMINICAN_REPUBLIC = "DOMINICAN REPUBLIC".freeze
    ECUADOR = "ECUADOR".freeze
    EGYPT = "EGYPT".freeze
    EL_SALVADOR = "EL SALVADOR".freeze
    EQUATORIAL_GUINEA = "EQUATORIAL GUINEA".freeze
    ERITREA = "ERITREA".freeze
    ESTONIA = "ESTONIA".freeze
    ESWATINI = "ESWATINI".freeze
    ETHIOPIA = "ETHIOPIA".freeze
    FALKLAND_ISLANDS__MALVINAS = "FALKLAND ISLANDS (MALVINAS)".freeze
    FAROE_ISLANDS = "FAROE ISLANDS".freeze
    FIJI = "FIJI".freeze
    FINLAND = "FINLAND".freeze
    FRANCE = "FRANCE".freeze
    GABON = "GABON".freeze
    GAMBIA = "GAMBIA".freeze
    GEORGIA = "GEORGIA".freeze
    GERMANY = "GERMANY".freeze
    GHANA = "GHANA".freeze
    GIBRALTAR = "GIBRALTAR".freeze
    GREECE = "GREECE".freeze
    GREENLAND = "GREENLAND".freeze
    GRENADA = "GRENADA".freeze
    GUATEMALA = "GUATEMALA".freeze
    GUINEA = "GUINEA".freeze
    GUINEA_BISSAU = "GUINEA-BISSAU".freeze
    GUYANA = "GUYANA".freeze
    HAITI = "HAITI".freeze
    HOLY_SEE = "HOLY SEE".freeze
    HONDURAS = "HONDURAS".freeze
    HONG_KONG = "HONG KONG".freeze
    HUNGARY = "HUNGARY".freeze
    ICELAND = "ICELAND".freeze
    INDIA = "INDIA".freeze
    INDONESIA = "INDONESIA".freeze
    IRAN__ISLAMIC_REPUBLIC_OF = "IRAN (ISLAMIC REPUBLIC OF)".freeze
    IRAQ = "IRAQ".freeze
    IRELAND = "IRELAND".freeze
    ISRAEL = "ISRAEL".freeze
    ITALY = "ITALY".freeze
    JAMAICA = "JAMAICA".freeze
    JAPAN = "JAPAN".freeze
    JORDAN = "JORDAN".freeze
    KAZAKHSTAN = "KAZAKHSTAN".freeze
    KENYA = "KENYA".freeze
    KIRIBATI = "KIRIBATI".freeze
    KOREA__DEMOCRATIC_PEOPLES_REPUBLIC_OF = "KOREA (DEMOCRATIC PEOPLE’S REPUBLIC OF)".freeze
    KOREA_REPUBLIC_OF = "KOREA, REPUBLIC OF".freeze
    KUWAIT = "KUWAIT".freeze
    KYRGYZSTAN = "KYRGYZSTAN".freeze
    LAO_PEOPLES_DEMOCRATIC_REPUBLIC = "LAO PEOPLE’S DEMOCRATIC REPUBLIC".freeze
    LATVIA = "LATVIA".freeze
    LEBANON = "LEBANON".freeze
    LESOTHO = "LESOTHO".freeze
    LIBERIA = "LIBERIA".freeze
    LIBYA = "LIBYA".freeze
    LIECHTENSTEIN = "LIECHTENSTEIN".freeze
    LITHUANIA = "LITHUANIA".freeze
    LUXEMBOURG = "LUXEMBOURG".freeze
    MACAO = "MACAO".freeze
    MACEDONIA = "MACEDONIA".freeze
    MADAGASCAR = "MADAGASCAR".freeze
    MALAWI = "MALAWI".freeze
    MALAYSIA = "MALAYSIA".freeze
    MALDIVES = "MALDIVES".freeze
    MALI = "MALI".freeze
    MALTA = "MALTA".freeze
    MAURITANIA = "MAURITANIA".freeze
    MAURITIUS = "MAURITIUS".freeze
    MEXICO = "MEXICO".freeze
    MOLDOVA_REPUBLIC_OF = "MOLDOVA, REPUBLIC OF".freeze
    MONACO = "MONACO".freeze
    MONGOLIA = "MONGOLIA".freeze
    MONTENEGRO = "MONTENEGRO".freeze
    MONTSERRAT = "MONTSERRAT".freeze
    MOROCCO = "MOROCCO".freeze
    MOZAMBIQUE = "MOZAMBIQUE".freeze
    MYANMAR = "MYANMAR".freeze
    NAMIBIA = "NAMIBIA".freeze
    NAURU = "NAURU".freeze
    NEPAL = "NEPAL".freeze
    NETHERLAND_ANTILLES = "NETHERLAND ANTILLES".freeze
    NETHERLANDS = "NETHERLANDS".freeze
    NEW_ZEALAND = "NEW ZEALAND".freeze
    NICARAGUA = "NICARAGUA".freeze
    NIGER = "NIGER".freeze
    NIGERIA = "NIGERIA".freeze
    NIUE = "NIUE".freeze
    NORFOLK_ISLAND = "NORFOLK ISLAND".freeze
    NORWAY = "NORWAY".freeze
    OMAN = "OMAN".freeze
    PAKISTAN = "PAKISTAN".freeze
    PANAMA = "PANAMA".freeze
    PAPUA_NEW_GUINEA = "PAPUA NEW GUINEA".freeze
    PARAGUAY = "PARAGUAY".freeze
    PERU = "PERU".freeze
    PHILIPPINES = "PHILIPPINES".freeze
    PITCAIRN = "PITCAIRN".freeze
    POLAND = "POLAND".freeze
    PORTUGAL = "PORTUGAL".freeze
    QATAR = "QATAR".freeze
    ROMANIA = "ROMANIA".freeze
    RUSSIAN_FEDERATION = "RUSSIAN FEDERATION".freeze
    RWANDA = "RWANDA".freeze
    SAINT_HELENA = "SAINT HELENA".freeze
    SAINT_KITTS_AND_NEVIS = "SAINT KITTS AND NEVIS".freeze
    SAINT_LUCIA = "SAINT LUCIA".freeze
    SAINT_VINCENT_AND_THE_GRENADINES = "SAINT VINCENT AND THE GRENADINES".freeze
    SAMOA = "SAMOA".freeze
    SAN_MARINO = "SAN MARINO".freeze
    SAO_TOME_AND_PRINCIPE = "SAO TOME AND PRINCIPE".freeze
    SAUDI_ARABIA = "SAUDI ARABIA".freeze
    SENEGAL = "SENEGAL".freeze
    SERBIA = "SERBIA".freeze
    SEYCHELLES = "SEYCHELLES".freeze
    SIERRA_LEONE = "SIERRA LEONE".freeze
    SINGAPORE = "SINGAPORE".freeze
    SINT_MAARTEN = "SINT MAARTEN".freeze
    SLOVAKIA = "SLOVAKIA".freeze
    SLOVENIA = "SLOVENIA".freeze
    SOLOMON_ISLANDS = "SOLOMON ISLANDS".freeze
    SOMALIA = "SOMALIA".freeze
    SOUTH_AFRICA = "SOUTH AFRICA".freeze
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS".freeze
    SOUTH_SUDAN = "SOUTH SUDAN".freeze
    SPAIN = "SPAIN".freeze
    SRI_LANKA = "SRI LANKA".freeze
    SUDAN = "SUDAN".freeze
    SURINAME = "SURINAME".freeze
    SWEDEN = "SWEDEN".freeze
    SWITZERLAND = "SWITZERLAND".freeze
    SYRIAN_ARAB_REPUBLIC = "SYRIAN ARAB REPUBLIC".freeze
    TAIWAN = "TAIWAN".freeze
    TAJIKISTAN = "TAJIKISTAN".freeze
    TANZANIA = "TANZANIA".freeze
    THAILAND = "THAILAND".freeze
    THE_BAHAMAS = "THE BAHAMAS".freeze
    TIMOR_LESTE = "TIMOR-LESTE".freeze
    TOGO = "TOGO".freeze
    TOKELAU = "TOKELAU".freeze
    TONGA = "TONGA".freeze
    TRINIDAD_AND_TOBAGO = "TRINIDAD AND TOBAGO".freeze
    TUNISIA = "TUNISIA".freeze
    TURKEY = "TURKEY".freeze
    TURKMENISTAN = "TURKMENISTAN".freeze
    TURKS_AND_CAICOS_ISLANDS = "TURKS AND CAICOS ISLANDS".freeze
    TUVALU = "TUVALU".freeze
    UGANDA = "UGANDA".freeze
    UKRAINE = "UKRAINE".freeze
    UNITED_ARAB_EMIRATES = "UNITED ARAB EMIRATES".freeze
    UNITED_KINGDOM = "UNITED KINGDOM".freeze
    UNITED_STATES = "UNITED STATES".freeze
    URUGUAY = "URUGUAY".freeze
    UZBEKISTAN = "UZBEKISTAN".freeze
    VANUATU = "VANUATU".freeze
    VENEZUELA = "VENEZUELA".freeze
    VIET_NAM = "VIET NAM".freeze
    WESTERN_SAHARA = "WESTERN SAHARA".freeze
    YEMEN = "YEMEN".freeze
    ZAMBIA = "ZAMBIA".freeze
    ZIMBABWE = "ZIMBABWE".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = CountryExtendedExpanded.constants.select { |c| CountryExtendedExpanded::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #CountryExtendedExpanded" if constantValues.empty?
      value
    end
  end
end
