# -*- encoding: utf-8 -*-

=begin
#Lob

#The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 

The version of the OpenAPI document: 1.3.0
Contact: lob-openapi@lob.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

$:.push File.expand_path("../lib", __FILE__)
require "openapi_client/version"

Gem::Specification.new do |s|
  s.name        = "lob"
  s.version     = Lob::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Lob"]
  s.email       = ["support@lob.com"]
  s.homepage    = "https://github.com/lob/lob-ruby"
  s.summary     = %q{Ruby wrapper for Lob.com API with ActiveRecord-style syntax}
  s.description = %q{Lob API Ruby wrapper}
  s.license     = "MIT"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
