=begin
#Lob

#The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 

The version of the OpenAPI document: 1.3.0
Contact: lob-openapi@lob.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Lob::IntlVerificationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IntlVerificationsApi' do
  before do
    # run before each test
    @api_instance = Lob::IntlVerificationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IntlVerificationsApi' do
    it 'should create an instance of IntlVerificationsApi' do
      expect(@api_instance).to be_instance_of(Lob::IntlVerificationsApi)
    end
  end

  # unit tests for bulk_intl_verifications
  # verifyBulk
  # Verify a list of international (except US or US territories) address with a live API key.
  # @param intl_verifications_payload 
  # @param [Hash] opts the optional parameters
  # @return [IntlVerifications]
  describe 'bulk_intl_verifications test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for intl_verification
  # verifySingle
  # Verify an international (except US or US territories) address with a live API key.
  # @param intl_verification_writable 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_lang_output * &#x60;native&#x60; - Translate response to the native language of the country in the request * &#x60;match&#x60; - match the response to the language in the request  Default response is in English. 
  # @return [IntlVerification]
  describe 'intl_verification test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
