=begin
#Lob

#The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 

The version of the OpenAPI document: 1.3.0
Contact: lob-openapi@lob.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Lob::UsVerificationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UsVerificationsApi' do
  before do
    # run before each test
    @api_instance = Lob::UsVerificationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsVerificationsApi' do
    it 'should create an instance of UsVerificationsApi' do
      expect(@api_instance).to be_instance_of(Lob::UsVerificationsApi)
    end
  end

  # unit tests for bulk_us_verifications
  # verifyBulk
  # Verify a list of US or US territory addresses with a live API key.
  # @param multiple_components_list 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :_case Casing of the verified address. Possible values are &#x60;upper&#x60; and &#x60;proper&#x60; for uppercased (e.g. \&quot;PO BOX\&quot;) and proper-cased (e.g. \&quot;PO Box\&quot;), respectively.
  # @return [UsVerifications]
  describe 'bulk_us_verifications test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for us_verification
  # verifySingle
  # Verify a US or US territory address with a live API key.
  # @param us_verifications_writable 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :_case Casing of the verified address. Possible values are &#x60;upper&#x60; and &#x60;proper&#x60; for uppercased (e.g. \&quot;PO BOX\&quot;) and proper-cased (e.g. \&quot;PO Box\&quot;), respectively.
  # @return [UsVerification]
  describe 'us_verification test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
